### ISSUE TITLE
failed launch

### ISSUE THREAD

**Issue by agusydk3** [MRHRTZ/DGC-ChatBotV3#1]
![image](https://user-images.githubusercontent.com/57493908/97447753-75df7400-1962-11eb-8372-e15227e43814.png)

**Comment by MRHRTZ** [comment]
@agusydk3 What are you sistem using? that's problem from the puppeter which can't locate the chrome browser

Try installing this

> wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
> sudo apt install ./google-chrome-stable_current_amd64.deb

Your options.js is default for Windows x86

and try edit <a href="https://github.com/MRHRTZ/DGC-ChatBotV3/blob/main/options.js#L33">This line</a> that located your chrome browser application

**Comment by MRHRTZ** [comment]
This is a normal issue, do like that and then run the code, if this still happen contact me on WhatsApp

Closing this issue for now thanks
